org: dyepesb
app: hello-world
service: hello-world

provider:
  name: aws
  runtime: nodejs14.x
  profile: test-iac
  region: us-west-2

plugins:
  - serverless-offline

functions:
  hello-world:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET